language: csharp
sudo: required
dist: trusty
os:
- linux
- osx
branches:
  except:
  - gh-pages
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
- 4.2.1
script:
- "./condo.sh --secure docs-deploy"
env:
  global:
    secure: ECernoEK+W36J0TSWJn1XkQzA4LkFrV8a6ocwj6b6dU48ps6vYLcC0sx6BwBtWQkBhCTVAK/JO1pc4bGh4PIPjjLdNF+RqwEofMlxlbPG2+pD39tair7XIZYpzbnQIZ2PjJxjOcEBXA6iBzbvekRYYRXucJjdaruTnVGUV5r2q7vHp0QWx2/mldUy7UAP6FUuH8BrsGidKHYzBoR42m17ab/3TipMYgma0tPAN9N/lS2Ra1DAZRYPKI8LPXGJaMAfeHcrjQ9I/r/mxP5lZNzwNGKeuaiOiBhkX6fXPh/k9pTeyUEBc3QVF/6RIVAAeR2eg9Q52qNW/3VKWRWNoXoeUjda4xPGfHb2gox/7hb8zbh+dxX7SCsdmGyjg9kHrGyFzPyV+P5EAEg1Khl3AiYrLok3U4qiVQu4ZfN1nH68UDJSdQVBzqP3FGdIiTcn8j9vx/1lpYCfMG9uygBBTp8P+tqgDC35XPrk+vaaKnSDcD3fKjuTUcKgGupp2TcBzo1RGX46XSaGJLGmNKS31FdNTQd/eATuKgqZfWfmxeRQtPmYwjSo68hI4bisHTKJGgl7GNNH+zyk2wq620L2xq234tqYFTPWl6C5mWEvVPIQdr4dDqoQqFgLyrxl+n8VOQkt9O59/KChyMYo+W2ZUg5Bs5jFGElWzYrl+a8icEZqvU=
notifications:
  webhooks:
    urls:
    - secure: dMhB7rWQO7yiMDxnc6G27skc79t/SPZyFZxwt1j0gWHVYe/PtPuo80cEafCLQGK7trJxUjgTKEqjSW/tPBiUHMbklWpExIDMr4jH7V2eHgYIH6/DmzlWXHdotsof25Yc9uFlUlkz4Ab4vPnVY/4HlQAgUakhKk053o3J+QRQmmdDVmqiPthGEo8JYFiQhRvzkWr4O2dmhCsys80lllEbedjmvle2w2bHMxWzKLWIPFy9j0uBNoOLFzuy0JqbRfGCFedPc5bRRrAFsISD4Shw84MZKM1QrUg283x2TXoEB+pl1FBVCiwGw+lavddRUPEo/l5U9ghQ/j7Vwr87KxPeQzMCDeOkASZpWfypX4/7XB4uOvYRRQLF7d0NZ1oS7E7VH5fqIZuevPfsHjtlUFtDEb4N/kvBLFsO7ay0QKJco/zgUgWb/cugmOX9SfdfIsoynibirHKUXw7BTiWOfI4OquhzUbGXwiR8lwvQO21NDBjVf1IZ99eVl54plTVHm8X3VZJTvz2yq2xnkRBGFz32Taa7o4KNwyqp/2HCy1N2t9qxwAGydDV2RZBCQcJr4FD4sgI3b5pbIoJjBLGeH50u2MGTqyZvKKnxYpUtABmkE/SYBWGqh3N5wSk0+0KJffLP0SqctfQtejNpzgDWCa7aLVTAPkfXyVuBz4IUPrK5XrA=
    - secure: Y9sC5qaWFkBFuTvrwX9gOAhN951UhhbKGT47JgyEOQU+Pzan2Hk00osLrUEUntdH4utHRx+IaJyrX/Tkwjxc5K8CCKHWrRzUPks4fPutlZOQoB/EPUmJLoiXv0GjfAUmAPY/Rxs1vKVbPoN0si1H/EqtelaWEBP1Bt4gfcC6opi3tHQcTy9OAKX3kkuHlHhRW03idpJ8TGWH8ggvzZ/6hgh5nDGFAPwrayrK9KJ9Kqwx6BggpfGioS1Qj5oGDPzS/SX3VBXH4IA5yE2baJWBpJghLuIMQXrGs9AseGrnYsl0lOSbbmYX7ccKPdD86x+b9zGni8YQCBeA195wrH0YMqhoibOqlbesBIvyFSID2xA4eKo1lsLWrOjO8j3aWfdBMzJhb9UnXTEQHevHMhYhPJGgKSuX9mYjL1tbbFhKKgcLHpEsgLvcsdysaSufRmc/5ckgHGof+kMfJzPKsitdqz/YpZeiPEAar6hGrv9XbfArv6SVITyNqizWCmFtVKFExpO9HSIu6buNRhfmg94rm34JoWxH+0okLSHsqs+ZonE4cXRcDNqU7EXL8L7C9MwWpz5v9Dy/A93Pz3/nxpqqKWo2x1yNanqktpd0G9mFtmQ3PPY/OKLZ+XsUUHEoiiDu0VEo6eh3Jnf4h/001a8nTfBcsHrR3vOjcfxMcqa4/Qw=
    on_success: always
    on_failure: always
    on_start: never