language: csharp
sudo: required
dist: trusty
os:
- linux
- osx
branches:
  except:
  - gh-pages
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
- 4.2.1
script:
- "./condo.sh --secure default docs-deploy"
env:
  global:
    secure: rAD/rJwOlr9UPIKmb9QWooyEcM0ahdmFcNK2avGG/X6uawgKKP6Dhqkt3HMkV8siVrVyrZODl1V4NNQWMA8vMFKOaEDwM0QTFn6AiLZhk884LGQe/pHk63PKhzofXUgv/fsNI/JcUzdZPr1CY07LGdC1rtkBEw79qofUDbEQr9KuiroWT/Qj7EiJ0mIEIH3USaLxt4Bs3zCB0ZMBU+M4g1p76u8XW03cCo1LvdK6KR4BKTiLtj226W7hMRq1acQYo/TWk9Ri10uloRXVKg09TcNSpHGW+rs5+CPH79/LfvSGmlbHIyXC46KcdEPkfefcjfplhv7OkxRl3AYGPmB2MoFhFkMKRbmus9lqyAjdgm+sOLIOz8DNcpIaBBSAhTfijarem5+8aFuZrN1G6tHJKvW+Ifhy4SwUBWc4VVkz6POmnLtyb5h7KQUS/BL41bSz2dy48dAKxHpYk40vC+50pxZ6e0U4HgZE1QOSBnn2IvHWIcqsId58naFASTlmX3SsMJhgvIbLJfXHCvpUReaHBISZdvS6qvFo42Mg9oIayVnZ/kQHw3Ivb6MXk2+LwPdZDra+rboK/3++8YYxCdJjG9vMYPtQdbYIJ6vSuLCfWFpoMoGHmf5+vPNFQOE4XJTh2UtVK4UkE+T2fhHa4RzAOoAD20wwliBFT9zYGGKgZgU=
notifications:
  webhooks:
    urls:
    - secure: dMhB7rWQO7yiMDxnc6G27skc79t/SPZyFZxwt1j0gWHVYe/PtPuo80cEafCLQGK7trJxUjgTKEqjSW/tPBiUHMbklWpExIDMr4jH7V2eHgYIH6/DmzlWXHdotsof25Yc9uFlUlkz4Ab4vPnVY/4HlQAgUakhKk053o3J+QRQmmdDVmqiPthGEo8JYFiQhRvzkWr4O2dmhCsys80lllEbedjmvle2w2bHMxWzKLWIPFy9j0uBNoOLFzuy0JqbRfGCFedPc5bRRrAFsISD4Shw84MZKM1QrUg283x2TXoEB+pl1FBVCiwGw+lavddRUPEo/l5U9ghQ/j7Vwr87KxPeQzMCDeOkASZpWfypX4/7XB4uOvYRRQLF7d0NZ1oS7E7VH5fqIZuevPfsHjtlUFtDEb4N/kvBLFsO7ay0QKJco/zgUgWb/cugmOX9SfdfIsoynibirHKUXw7BTiWOfI4OquhzUbGXwiR8lwvQO21NDBjVf1IZ99eVl54plTVHm8X3VZJTvz2yq2xnkRBGFz32Taa7o4KNwyqp/2HCy1N2t9qxwAGydDV2RZBCQcJr4FD4sgI3b5pbIoJjBLGeH50u2MGTqyZvKKnxYpUtABmkE/SYBWGqh3N5wSk0+0KJffLP0SqctfQtejNpzgDWCa7aLVTAPkfXyVuBz4IUPrK5XrA=
    - secure: Y9sC5qaWFkBFuTvrwX9gOAhN951UhhbKGT47JgyEOQU+Pzan2Hk00osLrUEUntdH4utHRx+IaJyrX/Tkwjxc5K8CCKHWrRzUPks4fPutlZOQoB/EPUmJLoiXv0GjfAUmAPY/Rxs1vKVbPoN0si1H/EqtelaWEBP1Bt4gfcC6opi3tHQcTy9OAKX3kkuHlHhRW03idpJ8TGWH8ggvzZ/6hgh5nDGFAPwrayrK9KJ9Kqwx6BggpfGioS1Qj5oGDPzS/SX3VBXH4IA5yE2baJWBpJghLuIMQXrGs9AseGrnYsl0lOSbbmYX7ccKPdD86x+b9zGni8YQCBeA195wrH0YMqhoibOqlbesBIvyFSID2xA4eKo1lsLWrOjO8j3aWfdBMzJhb9UnXTEQHevHMhYhPJGgKSuX9mYjL1tbbFhKKgcLHpEsgLvcsdysaSufRmc/5ckgHGof+kMfJzPKsitdqz/YpZeiPEAar6hGrv9XbfArv6SVITyNqizWCmFtVKFExpO9HSIu6buNRhfmg94rm34JoWxH+0okLSHsqs+ZonE4cXRcDNqU7EXL8L7C9MwWpz5v9Dy/A93Pz3/nxpqqKWo2x1yNanqktpd0G9mFtmQ3PPY/OKLZ+XsUUHEoiiDu0VEo6eh3Jnf4h/001a8nTfBcsHrR3vOjcfxMcqa4/Qw=
    on_success: always
    on_failure: always
    on_start: never
