init:
  - git config --global core.autocrlf true
build_script:
  - build.cmd --secure verify
clone_depth: 1
test: off
deploy: off
notifications:
- provider: Webhook
  url:
    secure: Gax9QyIw3MBLdedUK0jx/PHsp+ueN7DymrS/YDD7y8vaH5GrGOtCIQKNH3X0U3Yg8MXtsockpVOX+hoZO/VzKg==
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Webhook
  url:
    secure: Gax9QyIw3MBLdedUK0jx/C9AHdU7KWZ4V3/fyXbL5wn++QzjUaigsdRlDrJXmbz6W8xhsczxoxp8eqmYPUVYFw==
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true