init:
  - git config --global core.autocrlf true
build_script:
  - build.cmd --secure verify
clone_depth: 1
test: off
deploy: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/959cc86b71d0d9463066
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Webhook
  url: https://webhooks.gitter.im/e/74ab780e7b8298a8d2b5
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
